services:
  book-recommendation-app:
    build:
      context: .
      dockerfile: Dockerfile

    image: book-recommendation-app
    ports:
      - "8080:8080"
    volumes:
      - app_data:/app/uploads

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 7410
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7410
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  app_data:
  pg_data: